version: "2"

services:
  shell:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www/app/shell
    entrypoint: php
    volumes:
      - ./:/var/www
    networks:
      - backend
    links:
      - mysql
  console:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www/app
    entrypoint: php bin/console
    volumes:
      - ./:/var/www
    networks:
      - backend
    links:
      - mysql
  cli:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www/app
    entrypoint: bin/symfony
    volumes:
      - ./:/var/www
    networks:
      - backend
    links:
      - mysql
  composer:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www/app
    entrypoint: composer-11010.phar
    command: install --no-cache --no-progress -o --ignore-platform-reqs
    volumes:
      - ./:/var/www
      - ./bin:/usr/local/sbin
  composer_validate:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www/app
    entrypoint: composer-11010.phar
    command: validate --no-cache
    volumes:
      - ./:/var/www
      - ./bin:/usr/local/sbin
  fpm_status:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: php app/shell/fpm_status.php
    volumes:
      - ./:/var/www
    networks:
      - backend
    links:
      - php
  psalm:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: psalm-3131.phar --no-cache
    volumes:
      - ./:/var/www
      - ./bin:/usr/local/sbin
  psalm_taint:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: psalm-3131.phar --no-cache --taint-analysis
    volumes:
      - ./:/var/www
      - ./bin:/usr/local/sbin
  phpcsfixer:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: phpcsfixer-2164.phar fix --verbose --dry-run --diff --config phpcsfixer.conf
    volumes:
      - ./:/var/www
      - ./bin:/usr/local/sbin
  phpunit:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: php -dmemory_limit=64M -dextension=pcov.so /usr/local/sbin/phpunit-933.phar -c phpunit.xml --coverage-text --coverage-html=/var/coverage
    volumes:
      - coverage-data:/var/coverage
      - ./:/var/www
      - ./bin:/usr/local/sbin
    networks:
      - backend
    links:
      - nginx
      - php
      - mysql
  phploc:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: phploc-602.phar app/
    volumes:
      - ./:/var/www
      - ./bin:/usr/local/sbin
  apib2swagger:
    image: kminami/apib2swagger
    cap_drop: [all]
    working_dir: /docs
    command: -i api.md --prefer-reference --bearer-apikey -o swaggerui/swagger.json
    volumes:
      - ./docs:/docs

networks:
  backend:
    driver: bridge
